name: CI Pipeline for FastAPI App

# This triggers the workflow when there are pushes to the master branch or pull requests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # Using a latest Ubuntu runner

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t geo-log-app .

    # Run tests
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest

    - name: Set up Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly.io
      run: flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}